config/routes.rb
Scrunch::Application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  resources :services
  resources :providers do
    member { post :vote }
    resources :comments 
end

match 'contacts' => 'contacts#new', :as => 'contacts', :via => :get
match 'contacts' => 'contacts#create', :as => 'contacts', :via => :post

  root :to => 'services#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :name, :user_id
  belongs_to :provider
  belongs_to :user
end

app/models/message.rb
class Message
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  attr_accessible :street, :bio, :city, :insured, :name, :phone, :service_id, :state, :website, :zip, :latitude, :longitude
  
  geocoded_by :address 
    after_validation :geocode
    
    def address
       [street, city, state].compact.join(', ')
     end
     
  acts_as_gmappable :check_process => false, :process_geocoding => false
  def gmaps4rails_title
        'You found me!'
      end
  

  
  belongs_to :service
  belongs_to :user
  has_many :comments
  has_reputation :votes, source: :user, aggregated_by: :sum
  
  
  
  validates :name, :presence => true
  validates :insured, :presence => true
  validates :address, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true
  validates :phone, :presence => true
  validates :website, :presence => true
  validates :service_id, :presence => true
  validates :bio, :presence => true
  validates_length_of :bio, :maximum => 140
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :title, :category
  has_many :providers

  def self.search(search)
    search.blank? ? [] : all(:conditions => ['title LIKE ?', "%#{search.strip}%"])
end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :provider, :uid, :oauth_token, :oauth_expires_at
  # attr_accessible :title, :body
  has_many :comments, :dependent => :destroy
  
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    end
  end

  
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end
  
  def friends_count
    facebook.get_connection("me", "friends").size
  end
  
  def profile
    facebook.get_object("me")
  end
  
  def picture
    facebook.get_picture("uid")
  end
  
  def likes
     facebook.get_connection("me", "likes").size
   end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @provider = Provider.find(params[:provider_id])
      @comment = @provider.comments.build(params[:comment])
      @comment.user_id = current_user.id
      @comment.save!
      redirect_to provider_path(@provider)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      @message = Message.new
    end

    def create
      @message = Message.new(params[:message])

      if @message.valid?
        UserMailer.new_message(@message).deliver
        redirect_to(root_path, :notice => "Message was successfully sent.")
      else
        flash.now.alert = "Please fill all fields."
        render :new
      end
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in successfully."
      sign_in_and_redirect user, notice: "Signed in successfully."
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
  end
  
  def new
    @provider = Provider.new
  end
  
  def create
    @provider = Provider.new(params[:provider])
     if @provider.save
       						flash[:notice] = "Submission Successful"
       					else
       						flash[:notice] = "Hey there! looks like there was an error with your entry, please fill in all required fields."
       					end
       					render "new"
  end
  
  def edit
  end
  
  def update
  end
  
  def show
     @provider = Provider.find(params[:id])
     @json = Provider.find(params[:id]).to_gmaps4rails
  end
  
  def destroy
  end
  
  def vote
    value = params[:type] == "up" ? 1 : -1
      @provider = Provider.find(params[:id])
      @provider.add_or_update_evaluation(:votes, value, current_user)
      redirect_to :back, notice: "Thanks for voting!"
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  def index
    @services = Service.search(params[:search])
  end
  
  def new
    @service = Service.new
  end
  
  def create
    @service = Service.new(params[:service])
    @service.save
    redirect_to root_path
  end
  
  def edit
    @service = Service.find(params[:id])
  end
  
  def update
    @service = Service.find(params[:id])
    @service.update_attributes(params[:service])
    redirect_to root_path
  end
  
  def show
      @service = Service.find(params[:id])
      @providers = @service.providers.find_with_reputation(:votes, :all, order: "votes desc")
      @json = @service.providers.all.to_gmaps4rails
      
      if params[:search].present?
          @providers = @service.providers.near(params[:search], 50, :order => :distance)
          @json = @service.providers.near(params[:search], 50, :order => :distance).to_gmaps4rails
      end
  end
  
  def destroy
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  module UrlHelper
    def url_with_protocol(url)
      /^http/.match(url) ? url : "http://#{url}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for email, options = {}
      options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
      id = Digest::MD5::hexdigest email.strip.downcase
      url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
      options.delete :size
      image_tag url, options
  end
end

app/views/contacts/new.html.erb
<%= form_for @message, :url => contacts_path do |form| %>

<h2><center>Contact us</center></h2>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
<div class="topline"></div>	
<div class="container">	
	
	<%= link_to 'Home', root_path %> |
	<% if user_signed_in? %>
	  Signed in as <strong><%= current_user.username %></strong> |
	  <%= link_to 'Edit profile', edit_user_registration_path %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<br><br>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path %> |
	  <%= link_to "Login", new_user_session_path %> |
	<%= link_to "Submit your service", '/providers/new' %>
	<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>
	
	<div align="right">
	<%= link_to image_tag('fbsignin.gif'), user_omniauth_authorize_path(:facebook) %>
	</div>

   <% end %>
	<h2>ServiceCrunch</h2>

	<div class="row">
		<div class="span9">
			<div class="topline"></div>
		<%= yield %>
		
	
		</div>	
	</div>
</div>
<div class="beforebottom">
<div class="submit-service">
<%= link_to 'Contact us', contacts_path %>
</div>
</div>

<div class="bottom">

</div>
</body>
</html>

app/views/providers/new.html.erb
<% @title = "Submit your service"%>

<h3>Submit your service to ServiceCrunch:</h3>
<br>

<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2> Hey! We found <%= pluralize(@provider.errors.count, "issue") %> with your entry, please try again.</h2>	
<br>
      <ol>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>


<%= f.label "Type of service" %>
<%= f.collection_select :service_id, Service.all, :id, :title %><br><br>

<%= f.label :insured, 'Insured/Licensed? (Yes or No)' %>
<%= f.text_field :insured %>


<%= f.label :name %>
<%= f.text_field :name, :style => "width:660px;" %>

<%= f.label :street, 'Address' %>
<%= f.text_field :street, :style => "width:660px;" %>

<%= f.label :city %>
<%= f.text_field :city %>

<%= f.label :state %>
<%= f.text_field :state %>

<%= f.label :zip %>
<%= f.text_field :zip %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :website %>
<%= f.text_field :website, :style => "width:660px;", :placeholder => "start with http://"  %><br>

<div class="labels">
<span id="char-count">40</span> - 


<%= f.label :bio, 'Add a tagline for your service:' %> 
<div class="actions">
</div>	

<div class="field">
<%= f.text_area :bio, :rows => 4, :style => "width:660px;", :maxlength => 140 %>
</div>

<br>
<%= f.submit "Submit" %>  
<% end -%>

app/views/providers/show.html.erb
<% @title = @provider.name %>
<br>




<%= link_to "Back to list of providers", service_path(@provider.service_id) %><br><br>
<div>

<h4><%= @provider.name %></h4><br>
<%= @provider.street %><br>
<%= @provider.city %>,  <%= @provider.state %> <%= @provider.zip %><br>
<%= number_to_phone(@provider.phone)  %><br>
<%= link_to 'Company Website', @provider.website %><br>
Insured / licensed: <%= @provider.insured %>

<div class="row">
<div class="span9">
<div class="offset9 offset5">
<div class="googlemap">
	<%= gmaps("markers" => {"data" => @json}, "map_options" => {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 11}) %>
	<%= yield :scripts %>
</div>
</div>
</div>
</div>
<br>

<div class="topline"></div>
<br><br>
</div>

<%#--------start of comments iteration section-------------------- %>

<center><h4> Reviews for <%= @provider.name %></h4></center>
<br>


<% @provider.comments.reverse.each do |comment| %>
<%= gravatar_for comment.user.email if comment.user %>


<div style="margin-left: 7em; margin-top: -4em;">
<b><%= link_to comment.user.username, comment.user if comment.user %>:</b>
<%= comment.body %>



<div class="comment-ago">
<div align="right">
<%= time_ago_in_words(comment.created_at) %> ago
</div>
</div>
</div>
<hr>
<br><br><br>

<% end %>



<%#--------start of comments form section-------------------- %>

<h4>What was your experience with <%= @provider.name %>?</h4>
	
		<%= form_for ([@provider, @provider.comments.build]) do |f| %>
		  <div class="field">
		<%= f.text_area :body, :placeholder => "Add a comment...", :rows => 5, :style => "width:700px;" %></br>
		  </div>
		<%= f.submit 'Add Comment' %>
		<% end %>
 

app/views/services/edit.html.erb
<h3>Edit Service:</h3>

<%=form_for @service do |f| -%>
<%= f.label :title %>:
<%= f.text_field :title %>
<%= f.submit %>  
<% end -%>

app/views/services/index.html.erb
<% @title = 'ServiceCrunch' %>

<div class="search">
<form class="well form-search">
	<h4>What type of service are you looking for?</h4>
 <%= form_tag services_path, :method => 'get' do %>
	<%= text_field_tag :search, params[:search], :placeholder => "e.g. landscaping...", :style => "width:300px;" %>
	<%= submit_tag "Search", :name => nil %>	
<%end%>
</div>


<% @services.each do |service| %>  
    <p><%= link_to "#{service.title}", service %></p>
<% end %>
</form>

<div class="row">
<h2><center>Categories</center></h2>
<div class="span6">
<br>
	


	
<u><h4>Construction Services </h4></u>
<% Service.where(:category => "construction").each do |service| %>
<%= link_to service.title.capitalize, service %><br>
<% end %>

<br>

<u><h4>Pet Services </h4></u>
<% Service.where(:category => "pet").each do |service| %>
<%= link_to service.title.capitalize, service %><br>
<% end %>
<br><br>
</div>
</div>




</div>

app/views/services/new.html.erb
<% @title = "Add New Service" %>
<h3>Add New Service:</h3>
<br>

<%=form_for @service do |f| -%>
<%= f.label :title, 'Title of service:'  %>
<%= f.text_field :title %><br>

<%= f.label :category, "Create category:" %>
<%= f.text_field :category %><br>

<%= submit_tag "Send" %>
<% end -%>

app/views/services/show.html.erb
<% @title = @service.title %>
<div class="search">
<div class="row">
<div class="span9">
<form class="well form-search">
<%= form_tag service_path, :method => :get do %>
  <h4>Search for nearby <%= @service.title.downcase %> services by City, State or Zip:</h4> 
    <%= text_field_tag :search, params[:search], :placeholder => "e.g. Brooklyn, NY or 11223", :style => "width:300px;" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
</div>
</div>
</div>
</form>
<%= gmaps4rails(@json) %>
<br>

<h2><center><%= @service.title %></h2></center>
<br>

<br>
<ol>
<% if !@providers.empty? %>
<% @providers.each do |provider| %>

<li>
<%= link_to provider.name, provider_path(provider) %><br>
<%= provider.street %> <%= provider.city%> <%= provider.state%> <%= provider.zip%> <%= number_to_phone(provider.phone) %> <%= link_to 'website', provider.website  %>
</li>


<div class="vote">
<div align="right">
	<%= pluralize provider.reputation_value_for(:votes).to_i, "vote" %>
	<%= link_to "up", vote_provider_path(provider, type: "up"), method: "post" %>
| 	<%= link_to "down", vote_provider_path(provider, type: "down"), method: "post" %>


</div>
</div>

<hr>
<% end %>



<%= yield :scripts %>


<% else %>
Sorry there were no providers found near the address you specified.
<%end%>
</ol>